# 🔁 02_00.5 — DataFrame Skills: Repetition Edition
### Data Analyst Curriculum | Pandas Practice

---

### What this notebook is for
Every skill from 02_00 — but with **3 exercises each** instead of 1.
The goal is simple: by the end, reading a question should immediately
tell you which method to reach for.

### The dataset
A small bookstore — 10 orders. Small enough to see everything,
but with enough variety and duplicates to make groupby interesting.

---

## 🔧 Setup

In [ ]:
import pandas as pd

data = {
    'title':    ['Dune', 'Educated', '1984', 'Dune', 'Sapiens', 'Educated',
                 'The Alchemist', '1984', 'Sapiens', 'The Alchemist'],
    'genre':    ['sci-fi', 'memoir', 'sci-fi', 'sci-fi', 'nonfiction', 'memoir',
                 'fiction', 'sci-fi', 'nonfiction', 'fiction'],
    'price':    [18.00, 16.00, 12.00, 18.00, 20.00, 16.00, 14.00, 12.00, 20.00, 14.00],
    'quantity': [2, 1, 3, 1, 2, 4, 1, 2, 3, 2],
    'format':   ['hardcover', 'paperback', 'paperback', 'paperback', 'hardcover',
                 'paperback', 'paperback', 'hardcover', 'hardcover', 'paperback'],
}

df = pd.DataFrame(data)
# df # fix scrolling on my phone

## 🔍 Section 1: Inspecting a DataFrame

Quick reminder of the inspection tools:
- `df.shape` → (rows, columns)
- `df.info()` → column names, data types, non-null counts
- `df.describe()` → summary stats for numeric columns
- `df.head(n)` → first n rows
- `df.tail(n)` → last n rows
- `df.isnull().sum()` → count of missing values per column

### 🏋️ Exercise 1a
Print the number of rows and columns in `df` as a sentence.
Expected output: `"This dataset has 10 rows and 5 columns."`

```python
# Your code here
```

In [ ]:
# Your code here
print(f"this dataset has {df.shape[0]} rows and {df.shape[1]} columns")

this dataset has 10 rows and 5 columns


### 🏋️ Exercise 1b
Print only the column names and their data types.
*Hint: one of the inspection methods shows this.*

```python
# Your code here
```

In [ ]:
# Your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   title     10 non-null     object 
 1   genre     10 non-null     object 
 2   price     10 non-null     float64
 3   quantity  10 non-null     int64  
 4   format    10 non-null     object 
dtypes: float64(1), int64(1), object(3)
memory usage: 532.0+ bytes


### 🏋️ Exercise 1c
Print the average and maximum price using `df.describe()`.
Then verify those numbers by calling `.mean()` and `.max()` directly on the price column.

```python
# Your code here
```

In [ ]:
# Your code here
print(df['price'].describe())
print('average price:')
print(df['price'].mean())
print('max price:')
print(df['price'].max())


count    10.000000
mean     16.000000
std       2.981424
min      12.000000
25%      14.000000
50%      16.000000
75%      18.000000
max      20.000000
Name: price, dtype: float64
average price:
16.0
max price:
20.0


## 🎯 Section 2: Selecting Columns and Rows

Quick reminder:
- `df['col']` → one column (Series)
- `df[['col1', 'col2']]` → multiple columns (DataFrame)
- `df.iloc[n]` → row by position
- `df.loc[n]` → row by index label

### 🏋️ Exercise 2a
Select just the `title` and `price` columns and display them.

```python
# Your code here
```

In [ ]:
# Your code here
df[['title', 'price']]

,title,price
0,Dune,18.0
1,Educated,16.0
2,1984,12.0
3,Dune,18.0
4,Sapiens,20.0
5,Educated,16.0
6,The Alchemist,14.0
7,1984,12.0
8,Sapiens,20.0
9,The Alchemist,14.0


### 🏋️ Exercise 2b
Print the total quantity sold across all rows using the `quantity` column.
Then print the most expensive price in the dataset.

```python
# Your code here
```

In [ ]:
# Your code here
print(f"total amount of items sold: {df['quantity'].sum()}")
print(f"most expensive price: {df['price'].max():,.2f}")






total amount of items sold: 21
most expensive price: 20.00


### 🏋️ Exercise 2c
Retrieve the 3rd row using `.iloc[]` and the last row using `.iloc[]`.
Then retrieve the row with index label 7 using `.loc[]`.

```python
# Your code here
```

In [ ]:
# Your code here
print(f"3rd row item: \n{df.iloc[2]}")
print(f"last row item: \n{df.iloc[-1]}")
print(f"index 7: \n{df.loc[7]}")






3rd row item: 
title            Dune
genre          sci-fi
price            18.0
quantity            1
format      paperback
Name: 3, dtype: object
last row item: 
title       The Alchemist
genre             fiction
price                14.0
quantity                2
format          paperback
Name: 9, dtype: object
index 7: 
title            1984
genre          sci-fi
price            12.0
quantity            2
format      hardcover
Name: 7, dtype: object


## 🔎 Section 3: Filtering Rows

Quick reminder:
- `df[df['col'] == value]` → rows where condition is True
- `df[(condition1) & (condition2)]` → AND
- `df[(condition1) | (condition2)]` → OR

### 🏋️ Exercise 3a
Filter `df` to only hardcover books.
Print how many there are and their average price.

```python
# Your code here
```

In [ ]:
# Your code here

### 🏋️ Exercise 3b
Filter `df` to books priced at $15.00 or more.
Display the result — how many rows matched?

```python
# Your code here
```

In [ ]:
# Your code here

### 🏋️ Exercise 3c
Filter `df` to sci-fi books that are paperback.
Then filter `df` to books that are either memoir OR cost less than $14.00.
Print the row counts for both results.

```python
# Your code here
```

In [ ]:
# Your code here

## ➕ Section 4: Adding Columns with `.apply()`

Quick reminder:
```python
def my_function(value):
    return something

df['new_col'] = df['existing_col'].apply(my_function)
```
You pass the function name — no parentheses. Pandas calls it on every row.

### 🏋️ Exercise 4a
Write a function called `price_label` that returns:
- `'cheap'` if price is under $14.00
- `'mid'` if price is $14.00 to $17.99
- `'pricey'` if price is $18.00 or more

Apply it to the `price` column and store it in a new column called `price_label`.
Display `df` to confirm.

```python
# Your code here
```

In [ ]:
# Your code here

### 🏋️ Exercise 4b
Write a function called `is_bulk` that returns `True` if quantity is 3 or more,
and `False` otherwise.

Apply it to create a new column called `bulk_order`.
Then print how many bulk orders there are using `.sum()`.

```python
# Your code here
```

In [ ]:
# Your code here

### 🏋️ Exercise 4c
Write a function called `format_label` that returns:
- `'HC'` if the format is `'hardcover'`
- `'PB'` if the format is `'paperback'`

Apply it to create a new `short_format` column.
Then display only the `title`, `format`, and `short_format` columns to verify.

```python
# Your code here
```

In [ ]:
# Your code here

## 📊 Section 5: Summarizing with `.groupby()`

Quick reminder:
```python
df.groupby('group_col')['value_col'].aggregation()
```
Common aggregations: `.mean()` `.sum()` `.count()` `.min()` `.max()`

After groupby, the result is a Series — the group values become the index.

### 🏋️ Exercise 5a
Find the total quantity sold per genre.
Which genre had the most copies sold?

```python
# Your code here
```

In [ ]:
# Your code here

### 🏋️ Exercise 5b
Find the average price per format (hardcover vs paperback).
Print a sentence stating which format costs more on average.

```python
# Your code here
```

In [ ]:
# Your code here

### 🏋️ Exercise 5c
First add a `revenue` column (`price × quantity`).
Then find the total revenue per genre.
Display the results sorted highest to lowest.

```python
# Your code here
```

In [ ]:
# Your code here

## 🔢 Section 6: Finding Extremes with `.idxmax()` and `.idxmin()`

Quick reminder:
- `.idxmax()` → returns the **index label** of the highest value
- `.idxmin()` → returns the **index label** of the lowest value
- Use `.loc[]` to retrieve the full row using that label

Works on a plain column AND on the result of a groupby.

### 🏋️ Exercise 6a
Find the row with the highest quantity using `.idxmax()`.
Use `.loc[]` to retrieve that full row.
Print a sentence: `"The highest quantity order was X copies of [title]."`

```python
# Your code here
```

In [ ]:
# Your code here

### 🏋️ Exercise 6b
Find the row with the lowest price using `.idxmin()`.
Print the title and price of that book.

```python
# Your code here
```

In [ ]:
# Your code here

### 🏋️ Exercise 6c
Using the `revenue` column from Section 5:
1. Find the total revenue per title using `.groupby()`
2. Use `.idxmax()` on that result to find the best-selling title
3. Print: `"The best-selling title is [title] with $X in total revenue."`

```python
# Your code here
```

In [ ]:
# Your code here

## ⛓️ Section 7: Chaining Operations

Quick reminder — chain methods one after another, each working on the previous result:
```python
(df[df['col'] == value]
   .groupby('group_col')['value_col']
   .sum()
   .sort_values(ascending=False))
```
Outer parentheses let you split across lines.

### 🏋️ Exercise 7a
In one chain: filter to paperback books only, then find the total quantity per genre,
sorted highest to lowest.

```python
# Your code here
```

In [ ]:
# Your code here

### 🏋️ Exercise 7b
In one chain: filter to books priced over $15, then find the average revenue per genre.

```python
# Your code here
```

In [ ]:
# Your code here

### 🏋️ Exercise 7c
In one chain: filter to sci-fi books, find total revenue per title, sort descending.
Then print which sci-fi title earned the most.

```python
# Your code here
```

In [ ]:
# Your code here

## 🏁 Capstone: Bookstore Report

Answer all of the following using what you've practiced.
Then write 3–4 print statements presenting your findings to the bookstore owner.

1. What is the average revenue per genre? Which genre earns the most on average?
2. Among hardcover books only, which title has the highest total revenue?
3. What percentage of orders are bulk orders? *(bulk = quantity ≥ 3)*
4. Which format (hardcover or paperback) generates more total revenue?

```python
# Your code here
```

In [ ]:
# Your code here

---
## ✅ Done

If you could work through all of those without getting stuck, you're ready for 02_01.
The insurance dataset is just bigger — the operations are identical.